CREATE TABLE todos (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	title VARCHAR NOT NULL,
	body TEXT NOT NULL,
	completed BOOLEAN NOT NULL DEFAULT 'f',
	archived BOOLEAN NOT NULL DEFAULT 'f',
	todo_list_id UUID DEFAULT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
